FROM openjdk:17-jdk
ARG JAR_FILE=build/libs/yeohaenghama-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} docker-springboot.jar
ENTRYPOINT ["java","-jar","/docker-springboot.jar"]


ENV MYSQLSERVER 43.202.208.22
ENV MYSQLUSERNAME root
ENV MYSQLPASSWORD yhhama
ENV REDISSERVER 43.202.208.22
ENV REDISPASSWORD YHhama
ENV REDISPORTNUM 6379