name: Combined CI/CD Workflow

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches: [ "main", "feature/*" ]

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Set Environment Variable
      - name: Set Environment Variable
        run: echo "SAVE_STATE_MESSAGE=YourMessageHere" >> $GITHUB_ENV

      # Build with Gradle
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      # Deploy to Cloud
      - name: Deploy to Cloud
        if: github.ref == 'refs/heads/main'
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: jintaek019/yeohaenghama-backend
          stage: main
          yaml: |
            name: yeohaenghama-backend
            app: java@17
            options:
              ports: 8080
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
          

      # Docker 이미지 빌드
      - name: Docker Image Build
        run: |
          docker build --platform linux/amd64 -t jintaeklim/yhhama .
        # 에러 발생 시 작업 중지
        continue-on-error: false

      # Docker 로그인
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Docker Hub 이미지 푸시
      - name: Docker Hub Push
        run: |
          docker push jintaeklim/yhhama
        # 에러 발생 시 작업 중지
        continue-on-error: false